src/Telemedicine.Web/Areas/Administrator/Models/SpecializationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Administrator.Models
{
    public class SpecializationViewModel
    {
        public int Id { get; set; }

        [DisplayName("Код")]
        public int Code { get; set; }

        [DisplayName("Название")]
        public string DisplayName { get; set; }
    }
}

src/Telemedicine.Web/Areas/Administrator/Controllers/SpecializationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Telemedicine.Core.Domain.Services;
using Telemedicine.Core.Models;
using Telemedicine.Web.Areas.Administrator.Models;

namespace Telemedicine.Web.Areas.Administrator.Controllers
{
    public class SpecializationController : Controller
    {
        private readonly ISpecializationService _specializationService;

        public SpecializationController(ISpecializationService specializationService)
        {
            _specializationService = specializationService;
        }

        public async Task<ActionResult> Index()
        {
            var specializationsModel = (await _specializationService.GetSpecializationsAsync())
                .Select(t => new SpecializationViewModel
                {
                    Id = t.Id,
                    Code = t.Code,
                    DisplayName = t.DisplayName
                });
                
            return View(specializationsModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(SpecializationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var specialization = new Specialization
                {
                    Code = model.Code,
                    DisplayName = model.DisplayName
                };

                await _specializationService.CreateAsync(specialization);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var specialization = await _specializationService.GetByIdAsync(id);
            if (specialization == null)
            {
                return HttpNotFound("specialization not found");
            }

            var specializationViewModel = new SpecializationViewModel
            {
                Id = specialization.Id,
                Code = specialization.Code,
                DisplayName = specialization.DisplayName
            };

            return View(specializationViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, SpecializationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var specialization = await _specializationService.GetByIdAsync(id);
                if (specialization == null)
                {
                    return HttpNotFound("specialization not found");
                }

                specialization.Code = model.Code;
                specialization.DisplayName = model.DisplayName;
                await _specializationService.UpdateAsync(specialization);

                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

src/Telemedicine.Web/Areas/Administrator/Views/Specialization/Create.cshtml
@model Telemedicine.Web.Areas.Administrator.Models.SpecializationViewModel
@{
    ViewBag.Title = "Специализация: создание";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Специализация: создание</h2>

@using (Html.BeginForm("Create", "Specialization", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(m => m.Code, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.Code)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DisplayName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DisplayName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DisplayName)
            </div>
        </div>
    </div>

    <div>
        <a href="@Url.Action("Index")" class="btn btn-default">Отмена</a>
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
}

src/Telemedicine.Web/Areas/Administrator/Views/Specialization/Edit.cshtml
@model Telemedicine.Web.Areas.Administrator.Models.SpecializationViewModel
@{
    ViewBag.Title = "Специализация: изменение информации";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Специализация: изменение информации</h2>
<hr />

@using (Html.BeginForm("Edit", "Specialization", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)

    <div class="form-horizontal">
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(m => m.Code, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Code)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DisplayName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DisplayName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DisplayName)
            </div>
        </div>
    </div>

    <div>
        <a href="@Url.Action("Index")" class="btn btn-default">Отмена</a>
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
}

src/Telemedicine.Web/Areas/Administrator/Views/Specialization/Index.cshtml
@model IEnumerable<Telemedicine.Web.Areas.Administrator.Models.SpecializationViewModel>
@{
    ViewBag.Title = "Справочники: Специализация";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Справочники: Специализация</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="bg-primary">
            <tr>
                <th>Ид</th>
                <th>Код</th>
                <th>Название</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => p.Id)</td>
                    <td>@Html.DisplayFor(m => p.Code)</td>
                    <td>@Html.DisplayFor(m => p.DisplayName)</td>

                    <td class="tb-btn-col">
                        <div class="btn-group">
                            <a href="@Url.Action("Edit", new {id = p.Id})" class="btn btn-success" title="Редактирование">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p>
    <a href="@Url.Action("Create")" class="btn btn-primary btn-lg">
        Создать специализацию <span class="glyphicon glyphicon-plus"></span>
    </a>
</p>