src/Telemedicine.Web/Areas/Administrator/Models/DoctorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Administrator.Models
{
    public class DoctorViewModel
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string  MiddleName { get; set; }

        public string Specialization { get; set; }

        public string Email { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/AddCalendarEventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class AddCalendarEventViewModel
    {
        public DateTime Date { get; set; }

        public int Duration { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/AddEventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telemedicine.Core.Models.Enums; 

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class AddEventViewModel
    {
        [DisplayName("Дата начала")]
        public DateTime Begin { get; set; }

        [DisplayName("Дата окончания")]
        public DateTime? End { get; set; }

        [DisplayName("Весь день")]
        public bool IsOnDate { get; set; }

        [DisplayName("Заголовок")]
        public string Title { get; set; }
 

        [DisplayName("Понедельник")]
        public bool Monday { get; set; }
        [DisplayName("Вторник")]
        public bool Tuesday { get; set; }
        [DisplayName("Среда")]
        public bool Wednesday { get; set; }
        [DisplayName("Четверг")]
        public bool Thursday { get; set; }
        [DisplayName("Пятница")]
        public bool Friday { get; set; }
        [DisplayName("Суббота")]
        public bool Saturday { get; set; }
        [DisplayName("Воскресенье")]
        public bool Sunday { get; set; }  
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/AppointmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class AppointmentViewModel
    {
        public int Id { get; set; }
        public string PatientFio { get; set; }

        public DateTime Date { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/AttachmentViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class AttachmentViewModel
    { 
        public string Description { get; set; } 

        public HttpPostedFileBase File { get; set; } 

    }
}

src/Telemedicine.Web/Areas/Doctor/Models/CalendarEventModelView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class CalendarEventModelView
    {
        public DateTime Date { get; set; } 
        public string Topic { get; set; }

        public string Comments { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/DoctorStatusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telemedicine.Core.Domain.Models;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class DoctorStatusViewModel
    {
        public DoctorStatus CurrentStatus { get; set; }

        public IEnumerable<DoctorStatus> AvailableStatuses { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class EventViewModel
    {
        public EventViewModel()
        {
            allDay = false; 
        }
         
        public string title { get; set; }
        public DateTime start { get; set; }
        public DateTime? end { get; set; }
        public string color { get; set; }
        public bool allDay { get; set; } 
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/MarkAsDeletedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class MarkAsDeletedViewModel
    {
        public int Id { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class PaymentViewModel
    {
        [DisplayName("Метод оплаты")]
        public int SelectedMethodId { get; set; }

        public IEnumerable<SelectListItem> PaymentMethodListItems { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/RecommendationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class RecommendationViewModel
    { 
        [DisplayName(@"Краткое описание")]
        public string RecommendationText { get; set; }  

        public string PatientUserId { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/RecommendationViewModel2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class RecommendationViewModel2
    {
        public DateTime Date { get; set; }

        public string DoctorFIO { get; set; }

        public string DoctorSpecialization { get; set; }

        public string Content { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/SelectPatientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class SelectPatientViewModel
    {
        public int SelectedPatientId { get; set; }

        [DisplayName("ФИО пациента")]
        public IEnumerable<SelectListItem> Patients { get; set; } 
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/SetStatusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Telemedicine.Core.Domain.Models;

namespace Telemedicine.Web.Areas.Doctor.Models
{
    public class SetStatusViewModel
    {
        public DoctorStatus Status { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/Timetable/TimelineDateViewModel.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Telemedicine.Web.Areas.Doctor.Models.Timetable
{
    public class TimelineDateViewModel
    {
        //[JsonProperty("date")]
        public DateTime Date { get; set; }

       // [JsonProperty("hasConsultations")]
        public bool HasConsultations { get; set; }

        //[JsonProperty("hours")] 
        public List<TimelineHourViewModel> Hours { get; set; }
    }
}

src/Telemedicine.Web/Areas/Doctor/Models/Timetable/TimelineHourViewModel.cs
using System;
using Newtonsoft.Json;
using Telemedicine.Core.Models;

namespace Telemedicine.Web.Areas.Doctor.Models.Timetable
{
    public class TimelineHourViewModel
    {
        //[JsonProperty("hour")]
        public int Hour { get; set; }

        //[JsonProperty("hourType")]
        public DoctorTimetableHourType HourType { get; set; }

        //[JsonProperty("patientsCount")]
        public int PatientsCount { get; set; }

        public string DateTime { get; set; }
    }
}

src/Telemedicine.Web/Areas/Administrator/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using Telemedicine.Core.Domain.Consts;
using Telemedicine.Core.Domain.Services;
using Telemedicine.Core.Extensions;
using Telemedicine.Core.Identity;
using Telemedicine.Web.Areas.Administrator.Models;
using Telemedicine.Core.Models;

namespace Telemedicine.Web.Areas.Administrator.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService _doctorService;
        private readonly SiteUserManager _userManager;

        public DoctorController(IDoctorService doctorService, SiteUserManager userManager)
        {
            _doctorService = doctorService;
            _userManager = userManager;
        }

        public async Task<ActionResult> Index()
        {
            var doctors = await _doctorService.GetAllAsync();

            var doctorsModel = doctors.Select(doctor => new DoctorViewModel
            {
                Id = doctor.Id,
                Email = doctor.User.Email,
                FirstName = doctor.User.FirstName,
                LastName = doctor.User.LastName,
                MiddleName = doctor.User.MiddleName,
                Specialization = doctor.Specialization.DisplayName
            });

            return View(doctorsModel);
        }

        public async Task<ActionResult> Create()
        {
            var specializations = await _doctorService.GetSpecializationsAsync();
            ViewBag.Specializations = specializations.Select(t => new SelectListItem
            {
                Text = t.DisplayName,
                Value = t.Id.ToString()
            });
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(DoctorCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new SiteUser
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    MiddleName = model.MiddleName,
                    UserName = model.Email,
                    Email = model.Email,
                    AvatarUrl = model.AvatarUrl
                };


                var identityResult = await _userManager.CreateAsync(user, model.Password);

                if (identityResult.Succeeded)
                {
                    var roleResult = await _userManager.AddToRoleAsync(user.Id, UserRoleNames.Doctor);
                    if (roleResult.Succeeded)
                    {
                        var doctor = new Core.Models.Doctor();
                        doctor.UserId = user.Id;
                        doctor.SpecializationId = model.SpecializationId;
                        doctor.Description = model.Description;
                        await _doctorService.CreateAsync(doctor);

                        return RedirectToAction("Index");
                    }

                    roleResult.Errors.ForEach(t => ModelState.AddModelError(string.Empty, t));
                }

                identityResult.Errors.ForEach(t => ModelState.AddModelError(string.Empty, t));
            }

            var specializations = await _doctorService.GetSpecializationsAsync();
            ViewBag.Specializations = specializations.Select(t => new SelectListItem
            {
                Text = t.DisplayName,
                Value = t.Id.ToString()
            });

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var doctor = await _doctorService.GetByIdAsync(id);
            if (doctor == null)
            {
                return HttpNotFound("doctor not found");
            }

            var specializations = await _doctorService.GetSpecializationsAsync();
            ViewBag.Specializations = specializations.Select(t => new SelectListItem
            {
                Text = t.DisplayName,
                Value = t.Id.ToString(),
                Selected = t.Id == doctor.SpecializationId
            });

            var doctorViewModel = new DoctorChangeViewModel
            {
                Id = doctor.Id,
                Email = doctor.User.Email,
                FirstName = doctor.User.FirstName,
                LastName = doctor.User.LastName,
                MiddleName = doctor.User.MiddleName,
                SpecializationId = doctor.SpecializationId,
                Description = doctor.Description
            }; 

            return View(doctorViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, DoctorChangeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doctor = await _doctorService.GetByIdAsync(id);
                if (doctor == null)
                {
                    return HttpNotFound();
                }

                var user = await _userManager.FindByIdAsync(doctor.UserId);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.MiddleName = model.MiddleName;
                user.Email = model.Email;
                user.AvatarUrl = model.AvatarUrl;

                var identityResult = await _userManager.UpdateAsync(user);
                if (identityResult.Succeeded)
                {
                    doctor.SpecializationId = model.SpecializationId;
                    doctor.Description = model.Description;
                    await _doctorService.UpdateAsync(doctor);

                    return RedirectToAction("Index");
                }

                foreach (var identityError in identityResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, identityError);
                }
            }

            var specializations = await _doctorService.GetSpecializationsAsync();
            ViewBag.Specializations = specializations.Select(t => new SelectListItem
            {
                Text = t.DisplayName,
                Value = t.Id.ToString()
            });

            return View(model);
        }
    }
}

src/Telemedicine.Web/Areas/Doctor/Controllers/ConversationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Telemedicine.Core.Domain.Services;
using Telemedicine.Core.Models;
using Telemedicine.Core.Models.Enums;

namespace Telemedicine.Web.Areas.Doctor.Controllers
{
    public class ConversationController : Controller
    {
        private readonly IConversationService _conversationService;
        private readonly IPaymentHistoryService _paymentService;
        private readonly IPatientService _patientService;
        private readonly IDoctorService _doctorService;

        public ConversationController(IConversationService conversationService, IPaymentHistoryService paymentService, IPatientService patientService, IDoctorService doctorService)
        {
            _conversationService = conversationService;
            _paymentService = paymentService;
            _patientService = patientService;
            _doctorService = doctorService;
        }

        //[HttpPost]
        //public async Task<ActionResult> Create(string targetUserId)
        //{
        //    var creatorId = HttpContext.User.Identity.GetUserId();
        //    var conversation = await _conversationService.BeginConversation(creatorId, targetUserId);

        //    var patient = await _patientService.GetByUserIdAsync(targetUserId);

        //    await _paymentService.CreateAsync(new PaymentHistory
        //    {
        //        ConversationId = conversation.Id,
        //        Date = conversation.Created,
        //        Patient = patient,
        //        PaymentType = PaymentType.Consultation,
        //        Value = -500
        //    });

        //    return Json(new { ConversationId = conversation.Id });
        //}

        public async Task<ActionResult> Open(string id)
        { 
            var conversation = await _conversationService.OpenConversation(id);
            if (conversation == null)
            {
                return HttpNotFound("An error has ocurred while conversation opening");
            }

            var currentUserId = HttpContext.User.Identity.GetUserId();
            var targetUser = conversation.Members.FirstOrDefault(t => t.Id != currentUserId);

            if (targetUser == null)
            {
                return HttpNotFound("Conversation doesnt contain target member");
            }


            var patient =  await _patientService.GetByUserIdAsync(targetUser.Id);
            var doctor =  await _doctorService.GetByUserIdAsync(currentUserId);
            ViewBag.TargetId = patient.Id;
            ViewBag.DoctorId = doctor.Id; 
            ViewBag.UserDisplayName = targetUser.DisplayName;
            ViewBag.UserAvatarUrl = targetUser.AvatarUrl;
            ViewBag.TargetUserId = targetUser.Id;
           
            ViewBag.ConversationId = conversation.Id;



            return View();
        }
    }
}

src/Telemedicine.Web/Areas/Administrator/Views/Doctor/Create.cshtml
@model Telemedicine.Web.Areas.Administrator.Models.DoctorCreateViewModel
@{
    ViewBag.Title = "Врач: регистрация";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Врач: регистрация</h2>

@using (Html.BeginForm("Create", "Doctor", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", type="email" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.FirstName, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LastName, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LastName, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.MiddleName, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MiddleName, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.MiddleName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.SpecializationId, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SpecializationId, (IEnumerable<SelectListItem>) ViewBag.Specializations, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.MiddleName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AvatarUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AvatarUrl, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AvatarUrl)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
    </div>
    
    <div>
        <a href="@Url.Action("Index")" class="btn btn-default">Отмена</a>
        <input type="submit" value="Сохранить" class="btn btn-primary"/>
    </div>
}

src/Telemedicine.Web/Areas/Administrator/Views/Doctor/Edit.cshtml
@model Telemedicine.Web.Areas.Administrator.Models.DoctorChangeViewModel
@{
    ViewBag.Title = "Врач: изменение информации";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Врач: изменение информации</h2>
<hr/>

@using (Html.BeginForm("Edit", "Doctor", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    
    <div class="form-horizontal">
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", type="email" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.MiddleName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MiddleName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MiddleName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.SpecializationId, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SpecializationId, (IEnumerable<SelectListItem>) ViewBag.Specializations, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.MiddleName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AvatarUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AvatarUrl, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AvatarUrl)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
    </div>

    <div>
        <a href="@Url.Action("Index")" class="btn btn-default">Отмена</a>
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
}

src/Telemedicine.Web/Areas/Administrator/Views/Doctor/Index.cshtml
@model System.Collections.Generic.IEnumerable<Telemedicine.Web.Areas.Administrator.Models.DoctorViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Зарегистрированные врачи</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="bg-primary">
        <tr>
            <th>Ид</th>
            <th>E-mail</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Отчество</th>
            <th>Специализация</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var p in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => p.Id)</td>
                <td>@Html.DisplayFor(m => p.Email)</td>
                <td>@Html.DisplayFor(m => p.FirstName)</td>
                <td>@Html.DisplayFor(m => p.LastName)</td>
                <td>@Html.DisplayFor(m => p.MiddleName)</td>
                <td>@Html.DisplayFor(m => p.Specialization)</td>

                <td class="tb-btn-col">
                    <div class="btn-group">
                        <a href="@Url.Action("Edit", new {id = p.Id})" class="btn btn-success" title="Редактирование">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

<p>
    <a href="@Url.Action("Create")" class="btn btn-primary btn-lg">
        Зарегистрировать нового <span class="glyphicon glyphicon-plus"></span>
    </a>
</p>